# Generated by Django 5.0.6 on 2024-06-23 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_populate_equipment_data'),
    ]

    operations = [
    ]
